- src/utils/windowMenu.ts
updates the url for the help docs
> update the help docs

- README.md
- src/utils/windowMenu.ts
Fixes https://app.zenhub.com/workspaces/pomerium-5f0d1eec340a620025c4dfa0/issues/pomerium/internal/596
> add copy/paste for macs

- desktop-client.iml
- package.json
- src/main.dev.ts
- src/package.json
Fixes #40 
Fixes a mac issue where you had to click twice on system tray when another window had focus.
> fixes issue with mac having to double click in system tray

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE
Add initial issue and PR templates.
> Add Issue Templates

- src/App.tsx
- src/renderer/window.ts
Auto-opens main window when starting app
Fixes https://github.com/pomerium/internal/issues/656
> automatically open main window on launch

- .erb/scripts/WriteMetadata.ts
- src/main.dev.ts
- src/main.prod.js.LICENSE.txt
- src/main/binaries.ts
- src/renderer/components/TopTabs.tsx
Adds versions and auto starts the cli
> add versions and auto start the cli

- .erb/scripts/DownloadBinaries.ts
- .eslintrc.js
- src/main.dev.ts
- src/renderer/components/Toast.tsx
- src/renderer/components/TopTabs.tsx
- src/renderer/icons/ExportJSON.tsx
- src/renderer/pages/ConnectionView.tsx
> add some logging info

- api.proto
- src/declare.d.ts
- src/renderer/pages/ConnectionView.tsx
- src/shared/pb/api.ts
- src/shared/pb/google/protobuf/timestamp.ts
Integrate listener status updates and timestamp from the cli
Requires branch wasaga/listener-events of the cli
> integrate cli changes for listener events and timestamp

- src/App.tsx
- src/renderer/components/SnackbarCloseButton.tsx
- src/shared/constants.ts
Adds a close button to the notifications
> add a close button to the notifications

- package.json
Bump cli to pick up latest API changes
n/a
> deps: update to cli v0.0.0-rc2

- src/main.dev.ts
- src/trayMenu/helper.ts
Removes the global shortcuts
Fixes: https://github.com/pomerium/internal/issues/712
> remove global shortcuts

- src/renderer/pages/ConnectForm.tsx
Replaces the label "Destination URL" with "Destination" and updates the helper text.
#68
> Update Destination field label and helper

- src/renderer/components/ConnectionRow.tsx
Remove capitalization of connection names.
Fixes #73
> remove row capitalization

- src/package.json
Bump to v0.16.1 for next release
n/a
> bump version for next release

- src/main.dev.ts
- src/renderer/pages/ConnectForm.tsx
- src/shared/validators.ts
Removes tags capitalization.
Fixes https://github.com/pomerium/desktop-client/issues/76
> remove tag capitalization

- src/renderer/components/TagFolderRow.tsx
- src/renderer/components/VirtualFolderRow.tsx
expands row when clicked. 
Fixes https://github.com/pomerium/internal/issues/713
> expand row on click

- src/main.dev.ts
Report to Sentry if API process was abnormally terminated or couldn't start.
Implements https://github.com/pomerium/internal/issues/738
> add error handler for api process quit

- package.json
> bump to 0.16.1 cli

- src/renderer/pages/ManageConnections.tsx
change icon
Fixes: https://github.com/pomerium/internal/issues/750
> add upload icon

- .github/workflows/publish.yml
- src/package.json
Update CI for renaming master branch to main.
Also bump the next release's target version.
n/a
> ci: rename master to main

- api.proto
- desktop-client.iml
- package.json
- src/renderer/components/CertDetails.tsx
- src/renderer/pages/ConnectForm.tsx
- src/renderer/pages/ConnectionView.tsx
- src/renderer/pages/ManageConnections.tsx
- src/shared/pb/api.ts
- yarn.lock
Adds UI for the client certs.
Requires CLI Bump 
Fixes #90
> adds client cert fields

- package.json
> deps: bump cli to v0.17

- package.json
- yarn.lock
Removes a workaround that is no longer needed as the library code was updated and fixed.
> remove workaround that is no longer needed

- src/main.dev.ts
prevent multiple apps from spawning
Fixes https://github.com/pomerium/internal/issues/776
> prevent app spawning multiple times (windows)

- .eslintrc.js
- src/main.dev.ts
- src/renderer/components/ConnectionRow.tsx
- src/renderer/components/ExportDialog.tsx
- src/renderer/components/TagFolderRow.tsx
- src/renderer/pages/ConnectionView.tsx
- src/renderer/pages/ManageConnections.tsx
- src/shared/constants.ts
Add a dialog when export is clicked. The dialog has a checkbox to include tags or not.
Fixes https://github.com/pomerium/internal/issues/807
Fixes https://github.com/pomerium/desktop-client/issues/98
Fixes https://github.com/pomerium/internal/issues/808
> export: support exporting connections with tags

- .github/workflows/publish.yml
- .github/workflows/test.yml
Adopt https://github.com/ossf/scorecard standards for default github token permissions.
https://github.com/pomerium/internal/issues/813
> ci: set explicit token permissions

- package.json
Bump CLI to 0.17.1
Fixes https://github.com/pomerium/pomerium/issues/3181
> bump cli to 0.17.1

- package.json
bump CLI to v0.17.4
Fixes https://github.com/pomerium/desktop-client/issues/122
> bump CLI to v0.17.4

- package.json
> bump cli to v0.18.0

- src/package.json
> bump desktop-client version to 0.18.0

- package.json
- src/package.json
Upgrade to v19.
Fixes https://github.com/pomerium/internal/issues/977
> upgrade to v19

- package.json
- src/renderer/pages/ConnectForm.tsx
Update the GUI for extended TCP support.
Fixes https://github.com/pomerium/internal/issues/1202
> extended tcp support

- src/renderer/pages/ConnectForm.tsx
Update help text of Pomerium URL field.
Fixes https://github.com/pomerium/internal/issues/1205
> tcp: update help text

- package.json
- yarn.lock
Updates some packages flagged by dependabot
> updates some packages for security

- package.json
- src/package.json
> bump to 0.21.0-rc1

- package.json
- src/package.json
> bump to v0.21.0-rc2

- package.json
- src/package.json
> set version to v0.21.0

- .gitignore
- CHANGELOG.md
- scripts/changelog.sh
> add changelog script

- src/shared/pb/api.ts
- src/shared/pb/google/protobuf/timestamp.ts
Run `yarn protoc` to update the generated proto code.
I think the ts-proto package was updated from 1.85.0 to 1.117.0 as part of #151 but the protoc script hasn't been run since then.
> update generated proto code

- package.json
- yarn.lock
Trying to resolve https://github.com/pomerium/desktop-client/security/dependabot/119
> upgrade sentry/electron to also upgrade sentry/browser for dependabot

- src/package.json
> ci: set version to v0.29.0

- .erb/scripts/DownloadBinaries.ts
- .github/workflows/publish.yml
- package.json
- src/package.json
Prepare for v0.30 release.
n/a
> update pomerium-cli to v0.30.1
