pomerium/desktop-client

- src/components/FieldWrapper.tsx
- src/pages/ConnectForm.tsx
This PR updates the tooltip text per feedback in https://github.com/pomerium/internal/issues/575. The updates are also made t the docs [here](https://github.com/pomerium/pomerium/pull/2561/commits/2436c007b6ca50e1ef91bd522fe0fe21cf510222).
This PR also updates the FieldWrapper component to so that the description field is of type ReactFragment, which lets us add text styling (among other things) to the help text. If this is :+1:  I can also style the other descriptions the same way. If not I'll remove it and un-style the description I used it with.
> Update Tooltip Helper Text

- .erb/scripts/DownloadBinaries.ts
- .erb/scripts/WriteMetadata.ts
- .gitignore
- package.json
Enable embedding build metadata such as `pomerium-cli` version or git commit hash.  Unfortunately there's no particularly direct way to pass this information into an electron-builder application, so this PR places the information into a new `metadata.json` file.  This file can then be referenced by the desktop UI elements similar to `package.json`.
The benefit of using a new file over `package.json` is that we (a) don't have to rewrite an existing file, which feels wrong (b) can avoid accidentally persisting transient changes to `package.json`
Details:
- Centralize upstream `pomerium-cli` version to top level `package.json`
- Add script to generate the new file (`./src/metadata.json`)
- Add new `metadata` command to run said script as a dependency for `yarn build`
- Ensure git ignores …
> deployment: embed build metadata

- .github/workflows/publish.yml
We're getting failures to update the draft release, despite using the recommended [release strategy](https://www.electron.build/configuration/publish#recommended-github-releases-workflow) of electron-builder.  There may be a bug/api limit we're encountering, as we're trying to build/upload 4 mac artifacts and 2 linux artifacts at once.
This change performs the release of each platform/architecture serially, which hopefully sidesteps the problem.  See related issue for more info.
https://github.com/electron-userland/electron-builder/issues/4940
> ci: build release artifacts individually

- src/renderer/components/ConnectionRow.tsx
- src/renderer/pages/ManageConnections.tsx
Adds a menu item to copy the port of connected listener in the list page
> add ability to copy port from list page

- src/renderer/components/ConnectionRow.tsx
- src/renderer/components/TagFolderRow.tsx
- src/renderer/components/VirtualFolderRow.tsx
Put the icon on the left so that the text would stay aligned with other rows
Fixes #56
> show the port in the list of listeners

- README.md
- package.json
The desktop client depends on the [cli binary](https://github.com/pomerium/cli) but may need development against an unreleased branch, commit, etc.
This PR adds a few yarn scripts to set up a checkout of the cli repo and maintain a build of the cli that `yarn start` will pick up during local development.
If we started persisting artifacts from every commit that lands on `main` in the cli repo, we could pull those by default.  However, that wouldn't help in the case of an active PR or branch.  Putting together some commands to easily build locally seemed like a good compromise that would address broader use cases.
n/a
> add opinionated dev setup scripts

- src/renderer/components/ConnectionRow.tsx
- src/renderer/components/Toast.tsx
- src/renderer/pages/ManageConnections.tsx
- src/shared/constants.ts
Adds highlight and toast when copying port/address
[Fixes 703](https://app.zenhub.com/workspaces/pomerium-5f0d1eec340a620025c4dfa0/issues/pomerium/internal/703)
> adds highlights and toast when copying port/address

- package.json
- src/package.json
Update package.json for [v0.16](https://github.com/pomerium/pomerium/releases/tag/v0.16.0) release of Pomerium Core.
n/a
> Bump packaging to v0.16

- src/main.dev.ts
- src/trayMenu/helper.ts
Remove icon adds shortcut for Add Connection page in the System Tray Menu
Fixes https://github.com/pomerium/internal/issues/657
> add a shortcut for Add Connection

- src/renderer/components/ConfirmationDialog.tsx
- src/renderer/components/TagFolderRow.tsx
Shows confirmation dialog before connections by tag are deleted. 
Fixes https://github.com/pomerium/internal/issues/724
> show confirmation dialog before deleting all connections by tag

- src/renderer/components/TagFolderRow.tsx
Updates punctuation in folder delete confirmation from `:` to `.` as requested in https://github.com/pomerium/internal/issues/724#issuecomment-1009544781
Resolves https://github.com/pomerium/internal/issues/724
> Update confirmation punctuation.

- package.json
- src/main.dev.ts
- src/renderer/window.ts
- yarn.lock
Adds Sentry crash reporter. It does not automatically capture exceptions happening in the main process, thus they need be explicitly reported. That, unfortunately means that entire code need be instrumented, as exceptions are ignored in many other places and would not be caught by `process.on('uncaughtException',...)`, but that's a start. 
Also, Sentry need be given certain grace period to spool the events to the server. 
https://github.com/pomerium/internal/issues/581
> add sentry

- src/renderer/pages/ConnectionView.tsx
cleanup connection state change messages 
Fixes https://github.com/pomerium/internal/issues/715
> cleanup connection messages

- src/main.dev.ts
Adds sentry dsn passing to api server. 
https://github.com/pomerium/cli/pull/29
> initialize api server with sentry dsn

- src/main.dev.ts
- src/renderer/components/TagFolderRow.tsx
- src/renderer/components/VirtualFolderRow.tsx
Add some extra protection when grpc errors come back. Prevents sentry crashes.
Also fix the row click so it works when you click in the center of the row.
Fixes https://app.zenhub.com/workspaces/pomerium-5f0d1eec340a620025c4dfa0/issues/pomerium/internal/745
> add extra protection in main thread

- .gitignore
- src/renderer/components/BeforeBackActionDialog.tsx
- src/renderer/pages/ConnectForm.tsx
Replaces discard button with back button on the Connection Form
Fixes https://github.com/pomerium/internal/issues/711
> replaces discard button with back button on connection edit form

- src/main.dev.ts
Fixes bug when error returned from export process res.data is undefined
Adds sentry id to the pop up message.
Fixes [#798](https://github.com/pomerium/internal/issues/798)
> add error check for export

- .github/workflows/notify-tap.yml
Notify homebrew-tap when there's a release.
Fixes https://github.com/pomerium/desktop-client/issues/117
> notify tap of releases

- package.json
- src/package.json
- yarn.lock
webpack and electron-builder were having issues building on MacOS 13 and had to be bumped. 
https://github.com/pomerium/desktop-client/pull/163/
> bump dependencies and version

- package.json
- src/package.json
- src/renderer/pages/ConnectForm.tsx
- src/renderer/pages/ConnectionView.tsx
- src/shared/theme.ts
- yarn.lock
Upgrades sentry to be more in line with current electron version
Fixes some UI bugs (wrong borderRadius and client cert form on new connections)
Updates metadata to correct version 0.21
Fixes https://github.com/pomerium/desktop-client/issues/170
> sentry upgrade, bug fixes

- src/renderer/components/TopBar.tsx
Fixes the call to get all records in the search bar.
It was getting unmounted and so it lost the event listener.
Used a one time event listener now.
Fixes #172
> fix search bar

- src/package.json
v0.21.0 was previously used, thus we need a different one.
> set version to 0.21.1

- .github/workflows/notify-tap.yml
Update the notify-tap.yml GitHub Action workflow to replace the deprecated `::set-output` command with the newer `$GITHUB_OUTPUT` file mechanism.
- https://github.com/pomerium/internal/issues/1511
> replace ::set-output in notify-tap action

- .eslintrc.js
Turn off the no-console rule and add the ignoreRestArgs option to the no-explicit-any rule. This should prevent the 3 existing lint warnings:
```
/home/runner/work/desktop-client/desktop-client/src/cli.ts
Warning:   32:39  warning  Unexpected console statement  no-console
Warning:   33:39  warning  Unexpected console statement  no-console
/home/runner/work/desktop-client/desktop-client/src/renderer/components/ExportDialog.tsx
Warning:   18:12  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
✖ 3 problems (0 errors, 3 warnings)
```
(from e.g. https://github.com/pomerium/desktop-client/actions/runs/6177042776/job/16767292926#step:5:88)
> avoid existing eslint warnings

- .erb/scripts/Notarize.js
- .github/workflows/publish.yml
It looks like the new `notarytool` requires both `appleApiKey` and `appleApiKeyId` parameters. Update Notarize.js and the publish.yml workflow accordingly.
- https://github.com/pomerium/desktop-client/issues/317
> update notarization parameters

- .eslintrc.cjs
- api.proto
- src/renderer/components/CertFilter.tsx
- src/renderer/pages/ConnectForm.tsx
- src/renderer/pages/ConnectionView.tsx
- src/shared/pb/api.ts
`pomerium-cli` now has new options for searching the system trust store for a client certificate: by default it will look for a certificate matching any trusted CA names from the TLS handshake, but additionally it can filter by a single Issuer Name attribute and/or a single Subject Name attribute.
Add corresponding UI to the Desktop Client:
- add a 'Client certificates' section heading under the 'Advanced settings' panel
- move existing file upload / text entry UI behind a nested accordion labelled 'Set client certificate manually'
- add a 'Search OS certificate store' toggle button (this corresponds to the `--client-cert-from-store` CLI option)
- add an 'Additional OS certificate store filters' nested accordion with Issuer Name and Subject Name settings (these correspond to the …
> UI for new client cert OS store options

- package.json
- yarn.lock
This includes a fix for CVE-2024-27303 in app-builder-lib.
See https://github.com/advisories/GHSA-r4pf-3v7r-hh55 for more details.
- https://github.com/pomerium/desktop-client/security/dependabot/98
> Bump electron-builder from 23.6.0 to 24.13.3

- package.json
As of electron-builder v24, there is a built-in notarization step for macOS builds. This notarization step expects a slightly different set of environment variable values compared with what the existing Notarize.js script uses, which causes an error.
Disable the built-in notarization step in electron-builder, so we continue using the existing Notarize.js script for now.
- https://github.com/pomerium/desktop-client/issues/397
> disable duplicate macOS notarization step

- package.json
- yarn.lock
Bump electron-rebuild from 2.3.5 to 3.2.9.
This should remove a transitive dependency on the 'request' package, which has an open security alert and is no longer maintained: https://github.com/pomerium/desktop-client/security/dependabot/77.
It looks like this also removes a transitive dependency on the 'tough-cookie' package, which has an associated security alert as well: https://github.com/pomerium/desktop-client/security/dependabot/83.
- https://github.com/pomerium/internal/issues/1642
> Bump electron-rebuild from 2.3.5 to 3.2.9

- src/renderer/pages/ConnectForm.tsx
Rework the connection page so that the new OS certificate store client cert options show only in macOS and Windows builds. (The underlying CLI option is not supported on Linux.)
- https://github.com/pomerium/desktop-client/issues/312
> show new client cert UI only on macOS and Windows

- package.json
- yarn.lock
This is to address a vulnerability in ws, which dependabot was unable to resolve because of a dependency constraint from webpack-dev-server.
> bump webpack-dev-server to address ws vulnerable version

- yarn.lock
- https://github.com/pomerium/desktop-client/security/dependabot/111
> upgrade lint-staged to allow upgrading micromatch

- yarn.lock
This upgrades the transitive dependency path-to-regexp from 0.1.10 to 0.1.12, which should resolve a Dependabot security alert for that package.
- https://github.com/pomerium/desktop-client/security/dependabot/121
> Bump express from 4.21.1 to 4.21.2

- .eslintrc.cjs
- api.proto
- package.json
- src/App.tsx
- src/main.dev.ts
- src/renderer/components/AdvancedSettingsAccordion.tsx
- src/renderer/components/NewConnectionButton.tsx
- src/renderer/components/TagSelector.tsx
- src/renderer/hooks/use-popover.ts
- src/renderer/pages/ConnectForm.tsx
- src/renderer/pages/ConnectionView.tsx
- src/renderer/pages/LoadForm.tsx
- src/renderer/pages/ManageConnections.tsx
- src/shared/constants.ts
- src/shared/ipc.ts
- src/shared/pb/api.ts
- src/shared/pb/google/api/http.ts
- src/shared/pb/google/protobuf/descriptor.ts
- src/shared/pb/google/protobuf/timestamp.ts
- src/trayMenu/helper.ts
- yarn.lock
This adds a new form to load connections from a Pomerium URL using the new routes discovery portal. TCP and UDP connections will be created automatically.
I attempted to make it preserve any manually edited settings that aren't directly set by the load form (like the listener address).
The Load Form has an advanced section similar to the regular form. Those connection options will be used for each of the created connections. (For example to disable TLS)
The inputs on this form are saved into local storage so the user can reload their connections quickly.
Other changes:
* the API protobuf was regenerated based on changes from https://github.com/pomerium/cli/pull/487
* I noticed while testing that loading the routes was a little racy, so I added some async helpers so we can wait for the …
> add load connections form

- api.proto
- src/main.dev.ts
- src/renderer/pages/ConnectForm.tsx
- src/shared/pb/api.ts
Adds the abitlity to set connections to start on app launch within Pomerium Desktop. 
Relies on https://github.com/pomerium/cli/pull/494
> (feat) add the ability to automatically run connections on startup

- .github/workflows/publish.yml
- src/package.json
https://pomerium-com.slack.com/archives/C012D1Q96TX/p1744312102858289?thread_ts=1744116868.986989&cid=C012D1Q96TX
https://linear.app/pomerium/issue/ENG-2220/not-able-to-upgrade-to-version-0290
> Explicitly target the Windows package to use --x64 flag

- package.json
- yarn.lock
This should resolve a dependabot alert on the @sentry/node package.
- https://github.com/pomerium/desktop-client/security/dependabot/123
> update @sentry/electron from to 5.7.0 to 5.12.0
